deleting : files; Making serverinfo work again (regional IP, no gameversion, in a table)
utrolig/prostats pull request #1
Opened 2021-09-14 17:25 UTC by donkz

2021-09-16 09:34 UTC, utrolig requested changes

2021-09-16 09:34 UTC, utrolig commented on src/pages/servers/ServerList/ServerList.module.css
>    flex-direction: column;
If you remove `display: flex`, `flex-direction: column` won't have any effect so you might aswell remove that aswell

2021-09-16 09:34 UTC, utrolig commented on src/pages/servers/ServerList/ServerList.module.css
>    right: 12px;
If you remove `position: absolute`, `top` and `right` do nothing so just remove those aswell

2021-09-16 09:34 UTC, utrolig commented on src/pages/servers/ServerList/ServerList.tsx
> +			<tr>
The `<tr>` elements should be wrapped by a `<tbody>` element to be valid HTML

2021-09-16 09:34 UTC, utrolig commented on src/pages/servers/ServerList/ServerList.tsx
> +			<tr>
The `key` needs to be on the first root node returned by the `.map` function

2021-09-17 15:01 UTC, donkz commented
Added a "proposed fixes" commit

2021-09-24 15:54 UTC, vincentjr commented on src/pages/servers/ServerList/ServerList.tsx
> +			   */}
You may want to consider handling the case where there is no data or there's an error

2021-09-24 16:21 UTC, vincentjr commented on src/pages/servers/ServerList/ServerList.tsx
> +			   */}
nvm i see what you're doing now

2021-09-26 02:38 UTC, merged